import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


data = pd.read_csv('supply_chain_data.csv')


data.columns = data.columns.str.strip().str.lower().str.replace(' ', '_')

st.sidebar.header("Filter the Data")
product_filter = st.sidebar.multiselect("Select Product Type", options=data['product_type'].unique(), default=data['product_type'].unique())
location_filter = st.sidebar.multiselect("Select Location", options=data['location'].unique(), default=data['location'].unique())


filtered_data = data[(data['product_type'].isin(product_filter)) & (data['location'].isin(location_filter))]

st.subheader("📥 Download Filtered Data")

csv = filtered_data.to_csv(index=False).encode('utf-8')
st.download_button(
    label="Download data as CSV",
    data=csv,
    file_name='filtered_supply_chain_data.csv',
    mime='text/csv',
)

st.title("📦 Supply Chain Management Dashboard")
st.markdown("### Demand & Supply Analytics for Fashion Products")


total_units_sold = filtered_data['number_of_products_sold'].sum()
total_revenue = filtered_data['revenue_generated'].sum()
average_cost = filtered_data['costs'].mean()

col1, col2, col3 = st.columns(3)
col1.metric("Total Units Sold", f"{total_units_sold}")
col2.metric("Total Revenue", f"₹{total_revenue:,.0f}")
col3.metric("Avg. Logistics Cost", f"₹{average_cost:,.2f}")


st.subheader("Units Sold by Product Type")
fig1, ax1 = plt.subplots()
sns.barplot(data=filtered_data, x='product_type', y='number_of_products_sold', estimator=sum, ci=None, ax=ax1)
st.pyplot(fig1)


st.subheader("Revenue Generated by Location")
fig2, ax2 = plt.subplots()
sns.barplot(data=filtered_data, x='location', y='revenue_generated', estimator=sum, ci=None, ax=ax2)
st.pyplot(fig2)


st.subheader("Defect Rates by Transportation Mode")
fig3, ax3 = plt.subplots()
sns.boxplot(data=filtered_data, x='transportation_modes', y='defect_rates', ax=ax3)
st.pyplot(fig3)

st.subheader("Product Cost vs Manufacturing Cost")
fig4, ax4 = plt.subplots()
sns.scatterplot(data=filtered_data, x='manufacturing_costs', y='costs', hue='product_type', ax=ax4)
st.pyplot(fig4)

st.subheader("Revenue vs Manufacturing Cost by Product Type")
fig5, ax5 = plt.subplots()
sns.barplot(data=filtered_data, x='product_type', y='revenue_generated', color='blue', label='Revenue', ax=ax5)
sns.barplot(data=filtered_data, x='product_type', y='manufacturing_costs', color='orange', label='Manufacturing Cost', ax=ax5)
ax5.legend()
st.pyplot(fig5)

st.subheader("Average Defect Rate by Supplier")
fig6, ax6 = plt.subplots()
avg_defects = filtered_data.groupby('supplier_name')['defect_rates'].mean().sort_values(ascending=False)
avg_defects.plot(kind='bar', ax=ax6)
ax6.set_ylabel("Avg. Defect Rate")
st.pyplot(fig6)

st.subheader("Order Quantity vs Stock Levels")
fig7, ax7 = plt.subplots()
sns.scatterplot(data=filtered_data, x='stock_levels', y='order_quantities', hue='product_type', ax=ax7)
st.pyplot(fig7)

st.markdown("---")
st.markdown("📊 Dashboard created by Rishab for internship SCM project.")
